version: 1.0.{build}
before_build:
  - .nuget\nuget.exe restore
build:
  project: Toxiproxy.Net.sln
  verbosity: detailed

environment:
    COVERALLS_REPO_TOKEN:  
       secure: 26bH2HPtzUIMzItgYkadz+zq96203FZn+70q1OHN0vX9tRQtzrpdHCmG0Hm8huLi

after_test: 
    - packages\OpenCover.4.5.3723\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\xunit.runner.console.2.0.0\tools\xunit.console.x86.exe" -targetargs:"Toxiproxy.Net.Tests\bin\debug\Toxiproxy.Net.Tests.dll -appveyor -noshadow" -output:coverage.xml
    - packages\coveralls.io.1.3.2\tools\coveralls.net.exe --opencover coverage.xml