version: 1.0.{build}
before_build:
  - .nuget\nuget.exe restore
build:
  project: Toxiproxy.Net.sln
  verbosity: minimal

environment:
    COVERALLS_REPO_TOKEN:  
       secure: 26bH2HPtzUIMzItgYkadz+zq96203FZn+70q1OHN0vX9tRQtzrpdHCmG0Hm8huLi

after_test: 
    - packages\OpenCover.4.5.3723\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\xunit.runner.console.2.0.0\tools\xunit.console.x86.exe" -targetargs:"Toxiproxy.Net.Tests\bin\debug\Toxiproxy.Net.Tests.dll -appveyor -noshadow" -output:coverage.xml
    - packages\coveralls.io.1.3.2\tools\coveralls.net.exe --opencover -f -r $env:COVERALLS_REPO_TOKEN coverage.xml
    - packages\coveralls.net.0.5.0\csmacnz.Coveralls.exe --opencover -i coverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID